config/routes.rb
Rails.application.routes.draw do
  root to: 'toppages#index'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'signup', to: 'users#new'

  
  resources :users, only: [:index, :show, :create] do
    member do
      get :likes
      get :likeds
    end
  end
  resources :shop_join, only: [:index]
  resources :items, only: [:index, :show, :new, :create, :destroy]
  resources :trades, only: [:create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  
  validates :title, presence: true, length: { maximum: 255 }
  validates :address, presence: true, length: { maximum: 255 }
  validates :content, presence: true, length: { maximum: 255 }
  validates :price, presence: true, numericality: {only_integer: true, greater_than_or_equal_to: 1}, length: { maximum: 255 }
  validates :stock, presence: true, numericality: {only_integer: true, greater_than_or_equal_to: 1}, length: { maximum: 255 }
  
  mount_uploader :photo, PhotoUploader

end

app/models/trade.rb
class Trade < ApplicationRecord
  belongs_to :user
  belongs_to :item
end

app/models/user.rb
class User < ApplicationRecord
  enum category: { user: 0, shop: 1 }
  before_save { self.email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  validates :address, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  has_many :items
  has_many :trades
  has_many :likes, through: :trades, source: :item
  
  def trade(item)
    self.trades.find_or_create_by(item_id: item.id)
  end

  def untrade(item)
    trade = self.trades.find_by(item_id: item.id)
    trade.destroy if trade
  end

  def like?(item)
    self.likes.include?(item)
  end
  
  def feed_likes
    Item.where(user_id: self.like_ids )
  end
  
  def liked?(item)
    self.likeds.include?(item)
  end
  
  def feed_likeds
    Item.where(user_id: self.liked_ids )
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

 include SessionsHelper
  private

  def require_user_logged_in
    unless logged_in?
      redirect_to login_url
    end
  end
  def counts(user)
    @count_items = user.items.count
    @count_likes = user.likes.count
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :require_user_logged_in, only: [:new, :create, :destroy]
  before_action :correct_user, only: [:destroy]
  
  def index
    if current_user.present? && current_user.shop?
      @items = current_user.items
    else
      @items = Item.order(id: :desc).page(params[:page])
    end
  end

  def show
    @item = Item.find(params[:id])
  end
  
  def new
    @item = Item.new
  end

  def create
    @item = current_user.items.build(item_params)
    if @item.save
      flash[:success] = '商品を投稿しました。'
      redirect_to @item
    else
      @items = current_user.items.order(id: :desc).page(params[:page])
      flash.now[:danger] = '商品の投稿に失敗しました。'
      render :new
    end
  end

  def destroy
    @item.destroy
    flash[:success] = '商品を削除しました。'
    redirect_back(fallback_location: root_path)
  end

private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:title, :address, :content, :price, :photo, :stock)
    end

    def correct_user
        @item = current_user.items.find_by(id: params[:id])
        unless @item
          redirect_to root_url
        end
    end
    
    
    
    
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = 'ログインに成功しました。'
      redirect_to @user
    else
      flash.now[:danger] = 'ログインに失敗しました。'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました。'
    redirect_to root_url
  end
  private

  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      # ログイン成功
      session[:user_id] = @user.id
      return true
    else
      # ログイン失敗
      return false
    end
  end
end

app/controllers/shop_join_controller.rb
class ShopJoinController < ApplicationController
  def index
  end
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
        @items = Item.limit(3).order('id DESC')
  end
end

app/controllers/trades_controller.rb
class TradesController < ApplicationController
  def create
    item = Item.find(params[:item_id])
    current_user.trade(item)
    flash[:success] = '購入希望に追加しました。'
    redirect_back(fallback_location: root_path)
  end

  def destroy
    item = Item.find(params[:item_id])
    current_user.untrade(item)
    flash[:success] = '購入希望を削除しました。'
    redirect_back(fallback_location: root_path)
  end
  
  
   private

  def require_user_logged_in
    unless logged_in?
      redirect_to login_url
    end
  end
  
  
  
  
  
  
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:index, :show, :likes, :likeds]
  before_action :correct_user, only: [:likes, :likeds]
  def index
    @users = User.order(id: :desc).page(params[:page]).per(25)
  end

  def show
    if @current_user.user?
      @user = User.find(params[:id])
      @items = @user.items.order(id: :desc).page(params[:page])
      counts(@user)
    end
    if @current_user.shop?
      @user = User.find(params[:id])
      @items = Item.where(user_id: current_user.id)
      counts(@user)
    end
  end


  def new
     @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = 'ユーザを登録しました。'
      redirect_to @user
    else
      flash.now[:danger] = 'ユーザの登録に失敗しました。'
      render :new
    end
  end
  

    def likes
      @user = User.find(params[:id])
      @items = @user.likes.page(params[:page])
      counts(@user)
    end


    def likeds
      @user = User.find(params[:id])
      @items = current_user.items.select{|item| Trade.where.not(user_id: current_user.id).pluck(:item_id).include?(item.id)} # お気に入り登録された商品のみを抽出する
      counts(@user) 
    end


  private

  def user_params
    params.require(:user).permit(:category, :name, :address, :email, :password, :password_confirmation)
  end

  def correct_user
      @user = User.find(params[:id])
      unless @user == current_user
      redirect_to "/users/#{current_user.id}"
      end
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_url(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
  end
end

app/views/items/_items.html.erb
<div class="container-fluid">
  <div class="row">
  <% items.each do |item| %>  
    <div class="col-md-4">
        <img class="mr-2 rounded" src="<%= gravatar_url(item.user, { size: 50 }) %>" alt="">      
        <div class="media-body">
        <%= link_to item.user.name, user_path(item.user) %> <span class="text-muted">posted at <%= item.created_at %></span>
          <div class="card" style="width:18rem">
          
          <%= image_tag item.photo.url, :alt => '', size: '286x220' if item.photo? %>
          
            <div class="card-body">
              <h5 class="card-title"><%= item.title %></h5>
              <h6 class="card-subtitle text-muted"><%= item.address %></h6>
              <p class="card-text"><%= item.stock %>個<br>&yen;<%= item.price %></p>
              <p class="text-muted"><%= item.content %></p>
              <a href="<%= item_path(item) %>" class="card-link">詳細を見る</a>
              <div>
            <% if logged_in? && current_user.user? %>
            <%= render 'trades/trade_button', item: item %>
            <% end %>
            </div>
            <div>
            <% if current_user == item.user %>
            <%= link_to "Delete", item, method: :delete, data: { confirm: "You sure?" }, class: 'btn btn-danger btn-sm' %>
            <% end %>
            </div>
            </div>
          </div>
        </div>
    </div>
  <% end %>
  </div>
</div>

app/views/items/index.html.erb
<% if logged_in? && current_user.shop? %>

<div class="container-fluid">
  <div class="row">
  <% @items.each do |item| %>  
    <div class="col-md-4">
        <img class="mr-2 rounded" src="<%= gravatar_url(item.user, { size: 50 }) %>" alt="">      
        <div class="media-body">
        <%= link_to item.user.name, user_path(item.user) %> <span class="text-muted">posted at <%= item.created_at %></span>
          <div class="card" style="width:18rem">
          <%= image_tag item.photo.url, :alt => '', size: '286x220' if item.photo? %>
            <div class="card-body">
              <h5 class="card-title"><%= item.title %></h5>
              <h6 class="card-subtitle text-muted"><%= item.address %></h6>
              <p class="card-text"><%= item.stock %>個<br>&yen;<%= item.price %></p>
              <p class="text-muted"><%= item.content %></p>
              <a href="<%= item_path(item) %>" class="card-link">詳細を見る</a>
              <div>
            <% if logged_in? && current_user.user? %>
            <%= render 'trades/trade_button', item: item %>
            <% end %>
            </div>
            <div>
            <% if current_user == item.user %>
            <%= link_to "Delete", item, method: :delete, data: { confirm: "You sure?" }, class: 'btn btn-danger btn-sm' %>
            <% end %>
            </div>
            </div>
          </div>
        </div>
    </div>
  <% end %>
  </div>
</div>

  <% else %>

    <%= render 'items/items', items: @items %>

  <% end %>
  
  

app/views/items/new.html.erb
<div class="text-center">
  <h1>投稿作成</h1>
</div>

<%= render 'form', item: @item %>

app/views/items/show.html.erb
<h1>商品詳細</h1>

        <div class="card" style="width:18rem">
        <%= image_tag @item.photo.url, :alt => '' if @item.photo? %>
        <div class="card-body">
          <h5 class="card-title"><%= safe_join(@item.title.split("\n"),tag(:br)) %></h5>
          <h6 class="card-subtitle text-muted"><%= safe_join(@item.address.split("\n"),tag(:br)) %></h6>
          <p class="card-text"><%= @item.stock %>個<br>&yen;<%= @item.price %></p>
          <p class="text-muted"><%= safe_join(@item.content.split("\n"),tag(:br)) %></p>
          
        </div>
        </div>
<div class="text-center">
<%= link_to '一覧に戻る', items_path %>
</div>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<header class="mb-4">
  <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
    <a class="navbar-brand" href="/">NO! Food Loss</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
      <ul class="navbar-nav">
        <% if logged_in? %>
          <% if current_user.user? %>
   
          <li class="nav-item dropdown">
            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown"><%= current_user.name %></a>
            <ul class="dropdown-menu dropdown-menu-right">
              <li class="dropdown-item"><%= link_to 'My page', user_path(current_user) %></li>
              <li class="dropdown-divider"></li>
              <li class="dropdown-item"><%= link_to 'Logout', logout_path, method: :delete %></li>
            </ul>
            </li>
            
            <% else %>
            <li class="nav-item dropdown">
            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown"><%= current_user.name %></a>
            <ul class="dropdown-menu dropdown-menu-right">
              <li class="dropdown-item"><%= link_to 'My page', user_path(current_user) %></li>
              <li class="dropdown-divider"></li>
              <li class="dropdown-item"><%= link_to '投稿する', new_item_path %></li>
              <li class="dropdown-item"><%= link_to 'Logout', logout_path, method: :delete %></li>
              </ul>
              </li>
            
              <% end %>
              
        <% else %>
        <li class="nav-item"><%= link_to '概要', root_path(anchor: 'about'), class: 'nav-link' %></li>
        <li class="nav-item"><%= link_to '使い方', root_path(anchor: 'use'), class: 'nav-link' %></li>
        <li class="nav-item"><%= link_to '商品一覧', items_path, class: 'nav-link' %></li>
        <li class="nav-item"><%= link_to 'ログイン', login_path, class: 'nav-link' %></li>
        <li class="nav-item"><%= link_to '会員登録', signup_path, class: 'nav-link' %></li>
        <li class="nav-item"><%= link_to 'お店の方はこちら', shop_join_index_path, class: 'nav-link' %></li>
        <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/shop_join/index.html.erb
<section id="top">
  <div class="jumbotron text-center">
      <div class="container">
        <h1>お店の方へ</h1>
      </div>
    </div>
</section>

<section id="use">
  <div class="text-left">
    <h2>使い方</h2>
  </div>
<div class="card-deck">
  <div class="card" style="width:18rem">
    <div class="text-center">
    <%= image_tag 'use1.png', :alt => '', :size => '80x80' %>
    </div>
  <div class="card-body">
    <h5 class="card-title">ロス発生の危機</h5>
    <h6 class="card-subtitle text-muted">Food Loss</h6>
    <p class="card-text">商品が売れ残りそうでロスが発生しそうです。</p>
  </div>
</div>

  <div class="card" style="width:18rem">
    <div class="text-center">
  <%= image_tag 'use2.png', :alt => '', :size => '80x80' %>
  </div>
  <div class="card-body">
    <h5 class="card-title">NO!Food Lossに掲載</h5>
    <h6 class="card-subtitle text-muted">Food Loss</h6>
    <p class="card-text">商品をサイトに掲載します。</p>
  </div>
  </div>

  <div class="card" style="width:18rem">
    <div class="text-center">
  <%= image_tag 'use3.png', :alt => '', :size => '80x80' %>
  </div>
  <div class="card-body">
    <h5 class="card-title">食べての登場</h5>
    <h6 class="card-subtitle text-muted">Food Loss</h6>
    <p class="card-text">欲しい！ひとが現れます。</p>
  </div>
  </div>

  <div class="card" style="width:18rem">
    <div class="text-center">
  <%= image_tag 'use4.png', :alt => '', :size => '80x80' %>
  </div>
  <div class="card-body">
    <h5 class="card-title">お店で受け渡し</h5>
    <h6 class="card-subtitle text-muted">Food Loss</h6>
    <p class="card-text">食品ロスが削減できました！</p>
  </div>
  </div>
  
</div>
</section>

<section id="case">
    <div class="center jumbotron">
  <div class="text-left">
    <h2>こんなときに使ってください</h2>
  </div>
<div class="card-deck">
  <div class="card" style="width:18rem">
    <div class="text-center">
    <%= image_tag 'use1.png', :alt => '', :size => '80x80' %>
    </div>
  <div class="card-body">
    <h5 class="card-title">客足が振るわない</h5>
    <h6 class="card-subtitle text-muted">Food Loss</h6>
    <p class="card-text">予想外の天気やイベントで、来店予測を読み違えてしまった…
    あまってしまいそうなお弁当やパンの売り切りにご活用ください！</p>
  </div>
</div>

  <div class="card" style="width:18rem">
    <div class="text-center">
  <%= image_tag 'use2.png', :alt => '', :size => '80x80' %>
  </div>
  <div class="card-body">
    <h5 class="card-title">予約のドタキャンがでてしまった</h5>
    <h6 class="card-subtitle text-muted">Food Loss</h6>
    <p class="card-text">たくさん仕込んだのに、お客さんが現れなかった…
    ユーザーに助けを求めてみてください！</p>
  </div>
  </div>

  <div class="card" style="width:18rem">
    <div class="text-center">
  <%= image_tag 'use3.png', :alt => '', :size => '80x80' %>
  </div>
  <div class="card-body">
    <h5 class="card-title">「ワケあり」の商品に</h5>
    <h6 class="card-subtitle text-muted">Food Loss</h6>
    <p class="card-text">味や品質には問題ないけれど、少し見た目が悪くなってしまった…
    不慮のハネモノや、試作品など、きっと理解のあるユーザーが食べてくれます！</p>
  </div>
  </div>

  <div class="card" style="width:18rem">
    <div class="text-center">
  <%= image_tag 'use4.png', :alt => '', :size => '80x80' %>
  </div>
  <div class="card-body">
    <h5 class="card-title">もったいない「端材」を活用</h5>
    <h6 class="card-subtitle text-muted">Food Loss</h6>
    <p class="card-text">食材のいつもは捨ててしまっている部分、一手間加えれば売れるかも？
    オリジナルの商品として出品してみてください！</p>
  </div>
  </div>
  </div>
</div>
</section>

<section id="benefits">
  <div class="text-left">
    <h2>メリット</h2>
<div class="card-deck">
  <div class="card" style="width:18rem">
      <div class="text-center">
    <%= image_tag 'use1.png', :alt => '', :size => '80x80' %>
    </div>
  <div class="card-body">
    <h5 class="card-title">ロスを減らして利益増！</h5>
    <h6 class="card-subtitle text-muted">Food Loss</h6>
    <p class="card-text">これまで捨ててしまっていた食品を、追加の利益に転換することができます。
    ゴミの処理費用も節約できるので、ダブルでお得！</p>
  </div>
</div>

  <div class="card" style="width:18rem">
      <div class="text-center">
  <%= image_tag 'use2.png', :alt => '', :size => '80x80' %>
  </div>
  <div class="card-body">
    <h5 class="card-title">エコなお店として認知向上！</h5>
    <h6 class="card-subtitle text-muted">Food Loss</h6>
    <p class="card-text">食品ロスや二酸化炭素排出の削減に貢献できます。
    環境配慮型のお店としてアピールできます。</p>
  </div>
  </div>

  <div class="card" style="width:18rem">
      <div class="text-center">
  <%= image_tag 'use3.png', :alt => '', :size => '80x80' %>
  </div>
  <div class="card-body">
    <h5 class="card-title">新規顧客につながる！</h5>
    <h6 class="card-subtitle text-muted">Food Loss</h6>
    <p class="card-text">新しいお客様にお店を発見してもらえます。
    商品がおいしければ、通常の来店にもつながるかも！？</p>
  </div>
  </div>

  <div class="card" style="width:18rem">
      <div class="text-center">
  <%= image_tag 'use4.png', :alt => '', :size => '80x80' %>
  </div>
  <div class="card-body">
    <h5 class="card-title">従業員満足度UP!</h5>
    <h6 class="card-subtitle text-muted">Food Loss</h6>
    <p class="card-text">商品を捨てるのは、従業員にとって大きなストレス。
    捨てる量を減らし、エコに貢献することで従業員の離職も抑えることができます。</p>
  </div>
  </div>
</div>
</div>
</section>


<div class="text-center">
 <%= link_to '会員登録', signup_path, class: 'btn btn-lg btn-primary' %>
 <%= link_to 'ログイン', login_path, class: 'btn btn-lg btn-primary' %>
</div>

app/views/toppages/index.html.erb
<section id="top">
 <% if logged_in? %>

<div class="jumbotron jumbotron-extend">
    <div class="container-fluid jumbotron-container">
      <div class="text-center">
        <h1 class="site-name">Welcome to the NO! Food Loss</h1>
        <p>『最後まで食べ切る』を応援する社会派サービス</p>
        </div>
    </div>
</div>

<% else %>

<div class="jumbotron jumbotron-extend">
    <div class="container-fluid jumbotron-container">
      <div class="text-center">
        <h1 class="site-name">Welcome to the NO! Food Loss</h1>
        <p>『最後まで食べ切る』を応援する社会派サービス</p>
        <%= link_to '会員登録', signup_path, class: 'btn btn-lg btn-primary' %>
        </div>
    </div>
</div>
<% end %>
</section>


<section id="about">
<div class="center jumbotron">
  <div class="text-left">
    <h2>NO! Food Lossとは</h2>
    <h4>「フードロス」削減のためのプラットフォーム</h4>
    <p>閉店間際など、まだおいしく安全に食べられるのに廃棄の危機に直面している食事を「食べ手」とつなぎ、
最後まで売り切ることを応援するプラットフォームです。</p>
  </div>
</div>
</section>

<section id="use">
  <div class="center jumbotron">
  <div class="text-left">
    <h2>使い方</h2>
<div class="card-deck">
  <div class="card" style="width:18rem">
    <div class="text-center">
    <%= image_tag 'use1.png', :alt => '', :size => '80x80' %>
    </div>
  <div class="card-body">
    <h5 class="card-title">お店を見つける</h5>
    <h6 class="card-subtitle text-muted">Food Loss</h6>
    <p class="card-text">近くで助けを求めているいるお店の商品を探そう。</p>
  </div>
</div>

  <div class="card" style="width:18rem">
    <div class="text-center">
  <%= image_tag 'use2.png', :alt => '', :size => '80x80' %>
  </div>
  <div class="card-body">
    <h5 class="card-title">購入希望を登録</h5>
    <h6 class="card-subtitle text-muted">Food Loss</h6>
    <p class="card-text">食べたい食事を見つけたら、欲しい！を登録をしよう。</p>
  </div>
  </div>

  <div class="card" style="width:18rem">
    <div class="text-center">
  <%= image_tag 'use3.png', :alt => '', :size => '80x80' %>
  </div>
  <div class="card-body">
    <h5 class="card-title">お店に行く</h5>
    <h6 class="card-subtitle text-muted">Food Loss</h6>
    <p class="card-text">商品をお店に取りに行こう。</p>
  </div>
  </div>

  <div class="card" style="width:18rem">
    <div class="text-center">
  <%= image_tag 'use4.png', :alt => '', :size => '80x80' %>
  </div>
  <div class="card-body">
    <h5 class="card-title">フードロスの削減！</h5>
    <h6 class="card-subtitle text-muted">Food Loss</h6>
    <p class="card-text">おいしい食事を持ち帰って楽しみましょう。</p>
  </div>
  </div>
</div>
</div>
</div>
</section>

<section id="items">
<div class="center jumbotron">
  <div class="text-left">
    <h2>商品一覧</h2>
  </div>

<%= render 'items/items', items: @items %>

<div class="text-center">
<a class="btn btn-primary btn-lg" href="/items" role="button">もっとみる »</a>
</div>
</div>
</section>

app/views/users/_users.html.erb
<% if users.any? %>
  <ul class="list-unstyled">
    <% users.each do |user| %>
      <li class="media">
        <img class="mr-2 rounded" src="<%= gravatar_url(user, { size: 50 }) %>" alt="">
        <div class="media-body">
          <div>
            <%= user.name %>
          </div>
          <div>
            <p><%= link_to 'View profile', user_path(user) %></p>
          </div>
        </div>
      </li>
    <% end %>
  </ul>
  <%= paginate users %>
<% end %>

app/views/users/likeds.html.erb
<% if logged_in? && current_user.user? %>

<div class="row">

  <div class="col-sm-12">
    <ul class="nav nav-tabs nav-justified mb-3">
      <li class="nav-item"><a href="<%= likes_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(likes_user_path(@user)) %>">購入希望一覧  <span class="badge badge-secondary"><%= @count_likes %></span></a></li>
      <li class="nav-item"><%= link_to '商品一覧', items_path, class: 'nav-link' %></li>
    </ul>
    <%= render 'items/items', items: @items %>
  </div>
</div>


<% else %>
<div class="row">
 
  <div class="col-sm-12">
    <ul class="nav nav-tabs nav-justified mb-3">
      <li class="nav-item"><a href="<%= likeds_user_path(@user) %>" class="nav-link">購入希望登録された一覧</a></li>
      <li class="nav-item"><%= link_to '掲載商品一覧', items_path, class: 'nav-link' %></li>
    </ul>
    <%= render 'items/items', items: @items %>
  </div>
</div>


<% end %>

app/views/users/likes.html.erb
<% if logged_in? && current_user.user? %>

<div class="row">
  <aside class="col-sm-4">
    <div class="card">
      <div class="card-header">
        <h3 class="card-title"><%= @user.name %></h3>
      </div>
      <div class="card-body">
        <img class="rounded img-fluid" src="<%= gravatar_url(@user, { size: 500 }) %>" alt="">
      </div>
    </div>
  </aside>
  <div class="col-sm-8">
    <ul class="nav nav-tabs nav-justified mb-3">
      <li class="nav-item"><a href="<%= likes_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(likes_user_path(@user)) %>">購入希望一覧  <span class="badge badge-secondary"><%= @count_likes %></span></a></li>
      <li class="nav-item"><%= link_to '商品一覧', items_path, class: 'nav-link' %></li>
    </ul>
    <%= render 'items/items', items: @items %>
  </div>
</div>


<% else %>
<div class="row">
  <aside class="col-sm-4">
    <div class="card">
      <div class="card-header">
        <h3 class="card-title"><%= @user.name %></h3>
      </div>
      <div class="card-body">
        <img class="rounded img-fluid" src="<%= gravatar_url(@user, { size: 500 }) %>" alt="">
      </div>
    </div>
  </aside>
  <div class="col-sm-8">
    <ul class="nav nav-tabs nav-justified mb-3">
      <li class="nav-item"><a href="#" class="nav-link">購入希望登録された一覧</a></li>
      <li class="nav-item"><%= link_to '掲載商品一覧（他者が投稿した商品も出てくる、deleteボタンは自分が投稿した商品のみ出る）', items_path, class: 'nav-link' %></li>
    </ul>
    <%= render 'items/items', items: @items %>
  </div>
</div>


<% end %>

app/views/users/show.html.erb
<% if current_user.user? %>

<div class="row">
  <aside class="col-sm-4">
    <div class="card">
      <div class="card-header">
        <h3 class="card-title"><%= @user.name %></h3>
      </div>
      <div class="card-body">
        <img class="rounded img-fluid" src="<%= gravatar_url(@user, { size: 500 }) %>" alt="">
      </div>
    </div>
  </aside>
  <div class="col-sm-8">
    <ul class="nav nav-tabs nav-justified mb-3">
      <li class="nav-item"><a href="<%= likes_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(likes_user_path(@user)) %>">購入希望一覧  <span class="badge badge-secondary"><%= @count_likes %></span></a></li>
      <li class="nav-item"><%= link_to '商品一覧', items_path, class: 'nav-link' %></li>
    </ul>
  </div>
</div>


<% else %>
<div class="row">
  <aside class="col-sm-4">
    <div class="card">
      <div class="card-header">
        <h3 class="card-title"><%= @user.name %></h3>
      </div>
      <div class="card-body">
        <img class="rounded img-fluid" src="<%= gravatar_url(@user, { size: 500 }) %>" alt="">
      </div>
    </div>
  </aside>
  <div class="col-sm-8">
    <ul class="nav nav-tabs nav-justified mb-3">
      <li class="nav-item"><a href="<%= likeds_user_path(@user) %>" class="nav-link">購入希望登録された商品</a></li>
      <li class="nav-item"><%= link_to '投稿した商品一覧', items_path, class: 'nav-link' %></li>
    </ul>
    
  </div>
</div>


<% end %>